Add workflow for testing the debian binary
PilzDE/psen_scan_v2 pull request #192
Opened 2021-05-07 16:04 UTC by martiniil

## Description

These changes help the developer preventing issues like #169.

The `debian` job builds the debian binary and stores it on GitHub.
The `launch-check` job installs the debian package in a fresh container and executes a simple launch test.

### Things to add, update or check by the maintainers before this PR can be merged.

- [ ] Public api function documentation
- [ ] Architecture documentation reflects actual code structure
- [ ] [Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)
- [ ] Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)
- [ ] Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))
- [ ] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [ ] CHANGELOG.rst updated
- [ ] Copyright headers
- [ ] Examples

### Review Checklist
- [ ] Soft- and hardware architecture (diagrams and description)
- [ ] Test review (test plan and individual test cases)
- [ ] Documentation describes purpose of file(s) and responsibilities
- [ ] Code (coding rules, style guide)

### Release planning (please answer)
- [ ] When is the new feature released?
- [ ] Which dependent packages do have to be released simultaneously?

2021-05-10 08:55 UTC, agutenkunst requested changes
Only small findings.

But what I don't get is how the name of the resulting deb is generated.
Looking at the artifact from this PR I see that the deb-file is named `ros-noetic-psen-scan-v2_0.2.1-0focal_amd64.deb` probably due to the version found in the package.xml

I suggest some renaming of the deb file bevor uploading the artifact without a name revealing its true origin. This would eventually confuse. Maybe naming the zip-file of the artifact could also be enough.

2021-05-10 08:55 UTC, agutenkunst commented on .github/workflows/ci_action_noetic_binary.yml
> +          sudo apt-get update && sudo apt install python3-bloom fakeroot dpkg-dev debhelper -y
Are you sure sudo is needed?

2021-05-10 08:55 UTC, agutenkunst commented on test/integration_tests/integrationtest_ros_scanner_launch.test
> +</launch>
Newline

2021-05-10 10:00 UTC, martiniil commented on .github/workflows/ci_action_noetic_binary.yml
> +          sudo apt-get update && sudo apt install python3-bloom fakeroot dpkg-dev debhelper -y
No, I did not think about it ...

2021-06-08 11:08 UTC, agutenkunst commented
@martiniil how are we on this? You waiting for me or I waiting for you? ;-)

2021-06-11 11:06 UTC, martiniil commented
> 
> 
> @martiniil how are we on this? You waiting for me or I waiting for you? ;-)

Ah. I still want to check the caching-ansatz.

2021-06-17 16:50 UTC, agutenkunst approved these changes
Thank you!

2021-06-17 16:51 UTC, merged