Add hardware tests for timestamp
PilzDE/psen_scan_v2 pull request #226
Opened 2021-08-05 09:06 UTC by martiniil

## Description

These changes add hardware tests to #223 

### Things to add, update or check by the maintainers before this PR can be merged.

- [ ] Public api function documentation
- [ ] Architecture documentation reflects actual code structure
- [ ] [Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)
- [ ] Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)
- [ ] Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))
- [ ] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [ ] CHANGELOG.rst updated
- [ ] Copyright headers
- [ ] Examples

### Review Checklist
- [ ] Soft- and hardware architecture (diagrams and description)
- [ ] Test review (test plan and individual test cases)
- [ ] Documentation describes purpose of file(s) and responsibilities
- [ ] Code (coding rules, style guide)

### Release planning (please answer)
- [ ] When is the new feature released?
- [ ] Which dependent packages do have to be released simultaneously?

### Hardware tests
_Unstrike the text below to enable automatic hardware tests if available. Otherwise use this as a request for the reviewer._
- [ ] ~Perform hardware tests~

2021-08-06 09:39 UTC, ct2034 requested changes

2021-08-06 09:39 UTC, ct2034 commented on test/hw_tests/hwtest_timestamp.py
> +        - is bounded by the laserscan-msg receipt time.
lower than the time the message was received

2021-08-06 09:39 UTC, ct2034 commented on test/hw_tests/hwtest_timestamp.py
> +    """ Check if the timestamp of the laserscan message
""" Check if the timestamp of the laserscan messages

2021-08-06 09:39 UTC, ct2034 commented on test/hw_tests/hwtest_timestamp.py
> +        while len(self.received_stamps) < DESIRED_NUMBER_OF_STAMPS:
to make the node behave nicely on ctrl-c add: `and not rospy.is_shutdown()`

2021-08-06 11:26 UTC, martiniil commented on standalone/test/acceptance_tests/acceptancetest_timestamps.md
> +The calculated timestamp of the laser-scan (first ray time) with scan counter `n` has to be greater than the timestamp of the last frame with scan counter `n-1` in wireshark and smaller than the time
It takes much effort. This is a first step.

2021-08-23 08:26 UTC, ct2034 approved these changes

2021-08-23 08:29 UTC, merged