Refactor/state machine args
PilzDE/psen_scan_v2 pull request #232
Opened 2021-09-16 12:02 UTC by agutenkunst

## Description
This is a minor step towards more readability. StateMachineArgs was introduced due to missing the existence of `

During Review please check with real hardware!

### Things to add, update or check by the maintainers before this PR can be merged.

- [ ] ~Public api function documentation~
- [ ] Architecture documentation reflects actual code structure
- [ ] ~[Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)~
- [ ] ~Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)~
- [ ] ~Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))~
- [ ] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [ ] CHANGELOG.rst updated
- [ ] Copyright headers
- [ ] ~Examples~

### Review Checklist
- [ ] ~Soft- and hardware architecture (diagrams and description)~
- [ ] Test review (test plan and individual test cases)
- [ ] ~Documentation describes purpose of file(s) and responsibilities~
- [ ] Code (coding rules, style guide)

### Release planning (please answer)
- [ ] ~When is the new feature released?~
- [ ] ~Which dependent packages do have to be released simultaneously?~

### Hardware tests
- [ ] Perform hardware tests

2021-09-17 09:00 UTC, rfeistenauer commented
Manual hardware test was successfull

2021-09-20 15:02 UTC, cdoehn requested changes
suggestions:
* remove the abbreviations CB, cb and replace them by the full word callback and Callback.
* link to MSM docu (see comment)
* introduce a TimeoutHandler data type (see comment)

2021-09-21 07:30 UTC, agutenkunst commented on standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
> +                                              const communication_layer::NewDataHandler& control_data_handler,
I choose to rename almost all handlers that are actually callbacks (no class) into `callback`, hope you are fine with that.

2021-09-21 07:31 UTC, agutenkunst commented on standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
> +                                              const communication_layer::NewDataHandler& data_data_handler,
I choose to rename almost all handlers that are actually callbacks (no class) into `callback`, hope you are fine with that.

2021-09-21 09:17 UTC, cdoehn approved these changes

2021-09-22 07:52 UTC, agutenkunst commented
@cdoehn ready to merge?

2021-09-23 08:02 UTC, merged