Add draft for new PinData class
PilzDE/psen_scan_v2 pull request #301
Opened 2022-01-05 17:05 UTC by martiniil

## Description

---

<details>
<summary>PR Checklist</summary>

### Things to add, update or check by the maintainers before this PR can be merged.

- [ ] Public api function documentation
- [ ] Architecture documentation reflects actual code structure
- [ ] [Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)
- [ ] Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)
- [ ] Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))
- [ ] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [ ] CHANGELOG.rst updated
- [ ] Copyright headers
- [ ] Examples

### Review Checklist
- [ ] Soft- and hardware architecture (diagrams and description)
- [ ] Test review (test plan and individual test cases)
- [ ] Documentation describes purpose of file(s) and responsibilities
- [ ] Code (coding rules, style guide)

### Release planning (please answer)
- [ ] When is the new feature released?
- [ ] Which dependent packages do have to be released simultaneously?

### Hardware tests
_Unstrike the text below to enable automatic hardware tests if available. Otherwise use this as a request for the reviewer._
- [ ] ~Perform hardware tests~

</details>

2022-01-13 11:23 UTC, rfeistenauer requested changes

2022-01-13 11:23 UTC, rfeistenauer commented on standalone/test/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data_helper.h
> +#endif  // PSEN_SCAN_V2_STANDALONE_TEST_IO_PIN_DATA_HELPER_H
missing newline

2022-01-13 11:23 UTC, rfeistenauer commented on standalone/test/unit_tests/api/unittest_io_state.cpp
> +  pin_data.inputPinState(5, 1, true);  // make sure to not use "unused" bits
then maybe assert for it afterwards?

2022-01-13 13:01 UTC, martiniil commented on test/unit_tests/unittest_io_state_rosconversions.cpp
> +    EXPECT_EQ(pin_state_count, 1) << "Wrong number of outputs with id " << pin.id() << " in the resulting Message";
```suggestion
    EXPECT_EQ(pin_state_count, 1u) << "Wrong number of outputs with id " << pin.id() << " in the resulting Message";
```

2022-01-13 13:01 UTC, martiniil commented on test/unit_tests/unittest_io_state_rosconversions.cpp
> +    EXPECT_EQ(pin_state_count, 1) << "Wrong number of inputs with id " << pin.id() << " in the resulting Message";
```suggestion
    EXPECT_EQ(pin_state_count, 1u) << "Wrong number of inputs with id " << pin.id() << " in the resulting Message";
```

2022-01-13 15:01 UTC, martiniil commented on standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data.h
>  };
We have now two ways of accessing the arrays with the same effect:
```
bool old_state = pin_data.inputPinState(4, 3);
pin_data.inputPinState(4, 3, true);
```
```
bool old_state = pin_data.inputState().at(4).test(3);
pin_data.inputState().at(4).set(3);
```
Do you think we have increased readability through the methods `inputPinState(...)`? If not, we could as well go back to the struct:
```
struct PinData
{
std::array<std::bitset<8>, NUMBER_OF_INPUT_BYTES> input_states{};
std::array<std::bitset<8>, NUMBER_OF_OUTPUT_BYTES> output_states{};
};
```

2022-01-13 15:21 UTC, martiniil commented on standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data.h
>  };
I think I like it better as a struct. The convenience methods are rarely used (in production code) anyways. The "set"-methods never and the "get"-methods only once.

2022-01-14 10:32 UTC, rfeistenauer approved these changes

2022-01-14 10:33 UTC, merged