Use libfmt for printing
PilzDE/psen_scan_v2 pull request #38
Opened 2020-09-30 07:39 UTC by agutenkunst

For more infos on libfmt see https://github.com/fmtlib/fmt

2020-09-30 12:29 UTC, martiniil requested changes
I like it.

2020-09-30 12:29 UTC, martiniil commented on include/psen_scan_v2/logging.h
> +    console_bridge::getOutputHandler()->log(fmt::format(__VA_ARGS__), level, file, line);                              \
I am missing the name argument.

2020-10-01 09:44 UTC, hslusarek commented
Looks good. Let's give it a try.

2020-10-01 17:47 UTC, agutenkunst commented on include/psen_scan_v2/logging.h
> +    console_bridge::getOutputHandler()->log(fmt::format(__VA_ARGS__), level, file, line);                              \
Yep is missed this. Fixed.

2020-10-01 18:27 UTC, merged